### ISSUE TITLE
Failed at parsing sokoban problems from

### ISSUE THREAD

**Issue by pevnak** [JuliaPlanners/PDDL.jl#11]
Hi,

I am absolute newbie and minimally exposed to planning (but I have good co-workers). I am interesting in representation of planning problems which would be "nice" to machine learning algorithms. I have tried to parse problems from this repository.
https://github.com/binleyyang/Sokoban
while domain description was parsed without an issue, I had troubles with parsing the problem. The first two has failed, I have not tested the others.

Thanks for looking at the problem.

Tomas

**Comment by ztangent** [comment]
It looks like those problem files have extraneous commas in the `:objects` list -- if you remove all the commas, you should be good!

**Comment by pevnak** [comment]
Isee, thanks a lot for prompt answer.
