### ISSUE TITLE
Constraints unintuitive?

### ISSUE THREAD

**Issue by jw3126** [JuliaPlanners/PDDL.jl#15]
Thanks a lot for this nice package. I was trying to solve a constrained problem and found it a bit tricky to do so.
* I could not include `:constraints` in the domain definition, only in the problem, is this expected?
* Also the constraints did not appear automatically in the goal. I had to do
```julia
StateConstrainedGoal(
    MinStepsGoal(get_goal(problem)), 
    get_constraints(problem).args,
)
```
The `.args` part feels like I am using internals?
Am I doing this correctly or is there a better way?

**Comment by ztangent** [comment]
Glad you like the package! Constrained planning is unfortunately not something PDDL.jl fully supports yet. I haven't implemented full parsing support for PDDL 3 LTL-style constraints, and so right now you can only specify constraints in the problem file, and they are only limited to `always` style constraints (i.e. constraints that must hold along every state of the plan).

To make things a little easier though, I've just added a few new constructors for the `StateConstrainedGoal` specification in https://github.com/JuliaPlanners/SymbolicPlanners.jl/commit/e4b2a1f22bca20fd1344db4d89c135394e85802c, so you should just be able to do:
```
spec = StateConstrainedGoal(problem)
```

I'll be making another patch release with this and other changes shortly. Hope this helps!

**Comment by jw3126** [comment]
Awesome! If you are interested in this I could make a doc PR with a little tutorial example of a constrained problem.
