### ISSUE TITLE
forall when PDDL failure

### ISSUE THREAD

**Issue by helen-of-troy** [JuliaPlanners/PDDL.jl#20]
domain = @pddl("
(define (domain switchesworld3)
  (:requirements :typing :negative-preconditions :conditional-effects)

  (:types switch room)

  (:predicates
   (switch_is_on ?switch - switch)
   (at_switch_room ?switch - switch ?room -room)  ; The switch is in the room.
  )

  (:action turn-on-in-a-room
   :parameters (?switch - switch ?room - room)
   :precondition (and
                   (at_switch_room ?switch ?room)
                   (not (switch_is_on ?switch))
				 )
   :effect       (forall (?switch1 - switch)
                     (when (at_switch_room ?switch1 ?room)
                         (and
			               (switch_is_on ?switch1)
			              )
		              )
		         )
  )
)")

LoadError: MethodError: Cannot `convert` an object of type Symbol to an object of type Var

Closest candidates are:
  convert(::Type{T}, ::T) where T
   @ Base Base.jl:64
  Var(::Union{UInt64, Symbol})
   @ Julog ~/.julia/packages/Julog/pgKEW/src/structs.jl:24
  Var(::Any)
   @ Julog ~/.julia/packages/Julog/pgKEW/src/structs.jl:24

in expression starting at In[59]:1

Stacktrace:
  [1] push!(a::Vector{Var}, item::Symbol)
    @ Base ./array.jl:1060
  [2] parse_typed_list(expr::Vector{Any}, T::Type, default::Symbol, parse_fn::typeof(identity))
    @ PDDL.Parser ~/.julia/packages/PDDL/bALZ3/src/parser/formulas.jl:75
  [3] parse_typed_vars (repeats 2 times)
    @ ~/.julia/packages/PDDL/bALZ3/src/parser/formulas.jl:88 [inlined]
  [4] parse_declaration(expr::Vector{Any})
    @ PDDL.Parser ~/.julia/packages/PDDL/bALZ3/src/parser/formulas.jl:50
  [5] parse_typed_list(expr::Vector{Any}, T::Type, default::Symbol, parse_fn::typeof(PDDL.Parser.parse_declaration))
    @ PDDL.Parser ~/.julia/packages/PDDL/bALZ3/src/parser/formulas.jl:75
  [6] parse_typed_declarations
    @ ~/.julia/packages/PDDL/bALZ3/src/parser/formulas.jl:104 [inlined]
  [7] parse_predicates(expr::Vector{Any})
    @ PDDL.Parser ~/.julia/packages/PDDL/bALZ3/src/parser/domain.jl:93
  [8] parse_header_field
    @ ~/.julia/packages/PDDL/bALZ3/src/parser/parser.jl:74 [inlined]
  [9] macro expansion
    @ ~/.julia/packages/ValSplit/MMCz3/src/ValSplit.jl:0 [inlined]
 [10] _valswitch(::Val{(:requirements, :types, :constants, :predicates, :functions, :domain, :objects, :init, :goal, :metric, :constraints)}, ::Val{2}, ::typeof(PDDL.Parser.parse_header_field), ::PDDL.Parser.var"#72#default_f#4"{Symbol}, ::Val{:domain}, ::Symbol, ::Vector{Any})
    @ ValSplit ~/.julia/packages/ValSplit/MMCz3/src/ValSplit.jl:95
 [11] parse_header_field(desc::Val{:domain}, fieldname::Symbol, expr::Vector{Any})
    @ PDDL.Parser ~/.julia/packages/ValSplit/MMCz3/src/ValSplit.jl:145
 [12] parse_description(desc::Symbol, expr::Vector{Any})
    @ PDDL.Parser ~/.julia/packages/PDDL/bALZ3/src/parser/descriptions.jl:18
 [13] parse_domain(expr::Vector{Any}, domain_type::Type)
    @ PDDL.Parser ~/.julia/packages/PDDL/bALZ3/src/parser/domain.jl:10
 [14] parse_domain
    @ ~/.julia/packages/PDDL/bALZ3/src/parser/domain.jl:6 [inlined]
 [15] parse_top_level
    @ ~/.julia/packages/PDDL/bALZ3/src/parser/parser.jl:41 [inlined]
 [16] macro expansion
    @ ~/.julia/packages/ValSplit/MMCz3/src/ValSplit.jl:0 [inlined]
 [17] _valswitch
    @ ~/.julia/packages/ValSplit/MMCz3/src/ValSplit.jl:95 [inlined]
 [18] parse_top_level
    @ ~/.julia/packages/ValSplit/MMCz3/src/ValSplit.jl:145 [inlined]
 [19] parse_pddl(expr::Vector{Any})
    @ PDDL.Parser ~/.julia/packages/PDDL/bALZ3/src/parser/parser.jl:145
 [20] parse_pddl(str::String)
    @ PDDL.Parser ~/.julia/packages/PDDL/bALZ3/src/parser/parser.jl:151
 [21] var"@pddl"(__source__::LineNumberNode, __module__::Module, str::AbstractString)
    @ PDDL.Parser ~/.julia/packages/PDDL/bALZ3/src/parser/parser.jl:160

    By the way, the problem is:

problem = @pddl("
(define (problem switches_problem1)
  (:domain switchesworld3)

  (:objects a b c - switch living-room kitchen - room)

  (:init
   (not (switch_is_on a))
   (not (switch_is_on b))
   (not (switch_is_on c))
   (at_switch_room a kitchen)
   (at_switch_room b living-room)
   (at_switch_room c living-room)
  )

  (:goal (and (switch_is_on b)))

)
")

**Comment by ztangent** [comment]
Based on the error message, it looks like the predicates aren't successfully being parsed, and I think it's because of the missing space after the hyphen `-` in `?room -room` (should be `?room - room`).

```
(at_switch_room ?switch - switch ?room -room) 
```

**Comment by helen-of-troy** [comment]
Thank you for your quick response.
I made the necessary correction to the PDDL for the domain and it worked.
In the future, I will endeavor to double check my PDDL before submitting additional GitHub issues.

**Comment by ztangent** [comment]
No worries! Will close this issue since this is resolved.
