### ISSUE TITLE
Action precondition `(not (= ?a ?b))` doesn't work

### ISSUE THREAD

**Issue by wmanning-cra** [JuliaPlanners/PDDL.jl#8]
Here's a test that replicates the issue:

```
julia> using PDDL

julia> test_dom = pddl"(define (domain TM)
          (:requirements :adl :fluents :derived-predicates)
          (:types Location)
          (:predicates
             (player_at ?loc - Location)
           )
           (:action a_move
              :parameters (?from ?to - Location)
              :precondition (and
                  (not (= ?from ?to))
                  (player_at ?from)
               )
               :effect (and
                   (not (player_at ?from))
                   (player_at ?to)
               )
           )
       )"
[printout of domain]
julia> test_prob = pddl"(define (problem P_TM) (:domain TM)
           (:objects
               L1 L2 L3 - Location
           )
           (:init (player_at L1) )
           (:goal (and
               (player_at L3)
           ) )
       )"
[printout of problem]
julia> test_state = PDDL.initstate(test_dom, test_prob)
[printout of state]
julia> PDDL.available(test_dom, test_state)
3-element Vector{Term}:
 a_move(l1, l2)
 a_move(l1, l1)
 a_move(l1, l3)
```

The action `a_move(l1, l1)` should be illegal due to the precondition `(not (= ?from ?to))`, and this can be confirmed with `available()`:

```
julia> PDDL.available(test_dom, test_state, test_dom.actions[:a_move], [ PDDL.Const(:l1), PDDL.Const(:l2) ])
true

julia> PDDL.available(tdom, test_state, test_dom.actions[:a_move], [ PDDL.Const(:l1), PDDL.Const(:l1) ])
false
```

**Comment by ztangent** [comment]
Thanks for catching this! I think this is to do with how I'm currently finding satisfying assignments for precondition formulae in the interpreter implementation, which is sensitive to the order in which preconditions appear (similar to Prolog, because a Prolog engine is being used under-the-hood).

As a hot-fix, could you try seeing if switching the order of the pre-conditions fixes the issue? That is, replace:
```
:precondition (and (not (= ?from ?to)) (player_at ?from))
```
with
```
:precondition (and (player_at ?from) (not (= ?from ?to)))
```

**Comment by wmanning-cra** [comment]
I just swapped them, and still get the same issue

**Comment by wmanning-cra** [comment]
I also noticed another bug if I replace `(not (= ?from ?to))` with `(not (player_at ?to))`. In this case, there are **no** available actions:

```
julia> test_dom = pddl"(define (domain TM)
          (:requirements :adl :fluents :derived-predicates)
          (:types
             Location
           )
          (:predicates
             (player_at ?loc - Location)
             (nearby ?a ?b - Location)
           )
           (:action a_move
              :parameters (?from ?to - Location)
              :precondition (and
                  (player_at ?from)
                  (not (player_at ?to))
               )
               :effect (and
                   (not (player_at ?from))
                   (player_at ?to)
               )
           )
       )"
[printout of domain]
julia> PDDL.available(test_dom, PDDL.initstate(test_dom, test_prob))
Term[]
```

**Comment by ztangent** [comment]
Okay I just pushed a commit that I believe fixes the issue! It was a bug in how the interpreter was handling negative preconditions.

**Comment by wmanning-cra** [comment]
Thanks for the fast response! Would it make sense to update the project version? I had some trouble getting `Pkg` to recognize the new commit and I assume that's why.

**Comment by ztangent** [comment]
For now I think you should do `add https://github.com/JuliaPlanners/PDDL.jl.git` rather than `add PDDL` to get `Pkg` to use the latest master branch instead of the registered one. There are still a number of changes I'm hoping to make in the near future, then I'll do a bugfix release.
